### ISSUE TITLE
"Expected check in " error when running on a file with workday lines

### ISSUE THREAD

**Issue by vjohansen** [soren/App-TimeClock#13]
timeclock
  Expected check in in line 5 at C:/perl/perl/site/lib/App/TimeClock/DailyReport.pm line 98, <$file> line 5.

On line 5 I have a 'h' line

    i 2013/11/13 08:30:00 cam
    o 2013/11/13 16:29:52 home
    i 2013/11/14 08:30:16 cam
    o 2013/11/14 16:09:56 home
    h 2013/11/15 08:54:33 7
    i 2013/11/15 08:50:35 cam
    o 2013/11/15 16:30:32 home
    i 2013/11/18 08:45:41 cam

On fridays timeclock writes a 7 to the file

  (setq timeclock-get-workday-function (lambda () (if (is-it-friday) (* 7 3600) timeclock-workday)))

**Comment by soren** [comment]
That's a timeclock feature I didn't know, that's why it's not implemented. I will look into fixing this.

**Comment by soren** [comment]
I've released a new version (0.10) that simply ignores the 'h' line.
