### ISSUE TITLE
Expected check in

### ISSUE THREAD

**Issue by paynito** [soren/App-TimeClock#24]
Hi, on first run I get
 /usr/local/sbin/timeclock.pl

                 =====================================
                 Daily Report Mon Oct  2 17:09:33 2017
                 =====================================

Expected check in in line 3 at /Library/Perl/5.18/App/TimeClock/Daily/Report.pm line 120, <$file> line 3.

I think that I already have one valid check in and out done by emacs(timeclock.el) in the default
~/.emacs.d/timeclock

**Comment by soren** [comment]
Could you attach or paste your timeclock file?

**Comment by paynito** [comment]
Hi, new error now.
    → timeclock.pl

                 =====================================
                 Daily Report Tue Oct  3 10:28:49 2017
                 =====================================

    * Mon 2017/10/02 (16:26:49 - 16:27:56) *
    +--------------------------------------------------------------+-------+
    | Total Daily Hours                                            |  0.02 |
    +--------------------------------------------------------------+-------+
    | test                                                         |  0.02 |
    +--------------------------------------------------------------+-------+

    Use of uninitialized value $mon in subtraction (-) at       /Library/Perl/5.18/App/TimeClock/Daily/Report.pm line 67, <$file> line 4.
    Month '-1' out of range 0..11 at /Library/Perl/5.18/App/TimeClock/Daily/Report.pm line 67.

**Comment by paynito** [comment]
i 2017/10/02 16:26:49 test
    o 2017/10/02 16:27:56 finished printing
    i 2017/10/02 17:19:32 test2
    o 2017/10/02 17:29:32

error: last dates were `2017-mm-dd`      not `/mm/dd`   fixed! (manually)   Is timeclock.el or timeclock-x.el logging with "-" instead of "/" ?

        → timeclock.pl
                 =====================================
                 Daily Report Tue Oct  3 10:34:43 2017
                 =====================================
        * Mon 2017/10/02 (16:26:49 - 17:29:32) *
        +--------------------------------------------------------------+-------+
        | Total Daily Hours                                            |  0.19 |
        +--------------------------------------------------------------+-------+
        | test                                                         |  0.02 |
        +--------------------------------------------------------------+-------+
        | test2                                                        |  0.17 |
        +--------------------------------------------------------------+-------+

        TOTAL = 0.19 hours
        PERIOD = 1 days
        AVERAGE = 0.19 hours/day

**Comment by paynito** [comment]
Message feature of timeclock-x.el breaks timeclock.pl
M-x timeclock-in
M-x timeclock-out  ;; enter first message "test again",  enter second message "help", save with C-c C-c
appends to .emacs.d/timelog

    i 2017/10/03 10:39:43 test3
    o 2017/10/03 10:40:06 test again

    >> 
    help

                 =====================================
                 Daily Report Tue Oct  3 10:40:58 2017
                 =====================================

        * Mon 2017/10/02 (16:26:49 - 17:29:32) *
        +--------------------------------------------------------------+-------+
        | Total Daily Hours                                            |  0.19 |
        +--------------------------------------------------------------+-------+
        | test                                                         |  0.02 |
        +--------------------------------------------------------------+-------+
        | test2                                                        |  0.17 |
        +--------------------------------------------------------------+-------+

        Expected check in in line 7 at /Library/Perl/5.18/App/TimeClock/Daily/Report.pm line 120, <$file> line 7.
